apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/kustomize/examples/helloWorld
# https://github.com/kubernetes-sigs/kustomize/tree/master/examples/helloWorld
#- github.com/kubernetes-sigs/kustomize/examples/helloWorld

patches:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: the-map
  data:
    altGreeting: "Good Afternoon!"
EOF
